# Copyright (c) 2023 Chilledheart

freebsd_task:
  skip: "changesIncludeOnly(
    '.circleci/**',
    '.github/**'
    )"

  name: FreeBSD

  matrix:
    - name: FreeBSD 13.2
      freebsd_instance:
        image_family: freebsd-13-2
      env:
        configure: -DCMAKE_BUILD_TYPE=Release

  env:
    CIRRUS_CLONE_DEPTH: 10

  pkginstall_script:
    - pkg update -f
    - pkg install -y cmake ninja pkgconf perl5 go llvm17-lite git
    - ln -sf /usr/include/c++/v1/unwind.h /usr/include/unwind.h
    - ln -sf /usr/include/c++/v1/unwind-arm.h /usr/include/unwind-arm.h
    - ln -sf /usr/include/c++/v1/unwind-itanium.h /usr/include/unwind-itanium.h
    - pkg install -y devel/py-jsonschema devel/py-Jinja2
  submodules_script:
    # unshallow must come first otherwise submodule may be get unshallowed
    - git fetch --tags --unshallow
    - git submodule update --init --depth 1
  configure_script:
    - export PATH="/usr/local/llvm17/bin:$PATH"
    - export CC=clang
    - export CXX=clang++
    - mkdir build
    - cd build
    - cmake -G Ninja -DBUILD_TESTS=on -DBORINGSSL_BUILD_TESTS=on ${configure} ..
  compile_script:
    - ninja -C build yass_cli yass_server yass_test all_tests bssl_shim handshaker
  test_script:
    # blackhole?
    - sysctl net.inet.tcp.blackhole
    # make sure we don't run blackhole != 0
    - sudo sysctl net.inet.tcp.blackhole=0
    - ninja -C build check
    - ninja -C build check_boringssl

macos_task:
  skip: "changesIncludeOnly(
    '.circleci/**',
    '.github/**'
    )"

  name: macOS arm64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  matrix:
    - name: macOS arm64 release
      env:
        configure: -DCMAKE_BUILD_TYPE=Release

  env:
    CIRRUS_CLONE_DEPTH: 10

  pkginstall_script:
    - echo ninja cmake go p7zip ${install_packages} | xargs -Ix -n1 echo brew '"x"' > /tmp/Brewfile
    - "while [[ $? == 0 ]]; do for i in 1 2 3; do brew update && brew bundle install --no-lock --file /tmp/Brewfile && break 2 || { echo Error: wait to try again; sleep 10; } done; false Too many retries; done"
  submodules_script:
    # unshallow must come first otherwise submodule may be get unshallowed
    - git fetch --tags --unshallow
    - git submodule update --init --depth 1
  configure_script:
    - mkdir build
    - cd build
    - cmake -G Ninja -DGUI=on -DBUILD_TESTS=on -DBORINGSSL_BUILD_TESTS=on ${configure} ..
  compile_script:
    - ninja -C build yass yass_test all_tests bssl_shim handshaker
  test_script:
    - ninja -C build check
    - ninja -C build check_boringssl
