# Copyright (c) 2023 Chilledheart

freebsd_task:
  skip: "changesIncludeOnly(
    '.circleci/**',
    '.github/**'
    )"

  name: FreeBSD

  matrix:
    - name: FreeBSD 13.2
      freebsd_instance:
        image_family: freebsd-13-2
      env:
        configure: -DCMAKE_BUILD_TYPE=Release

  env:
    CIRRUS_CLONE_DEPTH: 10

  pkginstall_script:
    - pkg update -f
    - pkg install -y cmake ninja pkgconf perl5 go llvm17-lite git
    - ln -sf /usr/include/c++/v1/unwind.h /usr/include/unwind.h
    - ln -sf /usr/include/c++/v1/unwind-arm.h /usr/include/unwind-arm.h
    - ln -sf /usr/include/c++/v1/unwind-itanium.h /usr/include/unwind-itanium.h
    - pkg install -y devel/py-jsonschema devel/py-Jinja2
  submodules_script:
    # unshallow must come first otherwise submodule may be get unshallowed
    - git fetch --tags --unshallow
    - git submodule update --init --depth 1
  configure_script:
    - export PATH="/usr/local/llvm17/bin:$PATH"
    - export CC=clang
    - export CXX=clang++
    - mkdir build
    - cd build
    - cmake -G Ninja -DBUILD_TESTS=on ${configure} ..
  compile_script:
    - ninja -C build yass_cli yass_server yass_test
  test_script:
    # blackhole?
    - sysctl net.inet.tcp.blackhole
    # make sure we don't run blackhole != 0
    - sudo sysctl net.inet.tcp.blackhole=0
    - ninja -C build check
