SRC_DIR := src
SRC_FILES := $(wildcard $(SRC_DIR)/*.cpp)
SRC_FILES += $(wildcard $(SRC_DIR)/*.hpp)
SRC_FILES += $(wildcard $(SRC_DIR)/core/*.cpp)
SRC_FILES += $(wildcard $(SRC_DIR)/core/*.hpp)
SRC_FILES += $(wildcard $(SRC_DIR)/crypto/*.cpp)
SRC_FILES += $(wildcard $(SRC_DIR)/crypto/*.hpp)
SRC_FILES += $(wildcard $(SRC_DIR)/cli/*.cpp)
SRC_FILES += $(wildcard $(SRC_DIR)/cli/*.hpp)
SRC_FILES += $(wildcard $(SRC_DIR)/server/*.cpp)
SRC_FILES += $(wildcard $(SRC_DIR)/server/*.hpp)
SRC_FILES += $(wildcard $(SRC_DIR)/gui/*.cpp)
SRC_FILES += $(wildcard $(SRC_DIR)/gui/*.mm)
SRC_FILES += $(wildcard $(SRC_DIR)/gui/*.hpp)
all: $(SRC_FILES)
	clang-format --style file -i $(SRC_FILES)
