# Copyright (c) 2023 Chilledheart

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  update-submodule:
    steps:
      - run:
          command: |
            git submodule update --init --depth 1

  download-toolchain:
    steps:
      - run:
          command: |
            curl -L -O https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
            tar -C third_party -xvf clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz \
              clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/lib/clang/12.0.1/include \
              clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin/{clang,clang++,clang-12,ld.lld,lld,llvm-ar,llvm-ranlib}
            rm -f *.xz

  download-toolchain-arm:
    steps:
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y clang

  install-deps:
    steps:
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y cmake ninja-build libgtk-3-dev libncurses5 gettext libcurl4-openssl-dev

  configure:
    steps:
      - run:
          command: |
            export "CC=$PWD/third_party/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin/clang"
            export "CXX=$PWD/third_party/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin/clang++"
            mkdir build
            cd build
            cmake -G Ninja -DGUI=on -DBUILD_TESTS=on -DCMAKE_BUILD_TYPE=Release ..

  configure-gcc:
    steps:
      - run:
          command: |
            export "CC=gcc"
            export "CXX=g++"
            mkdir build
            cd build
            cmake -G Ninja -DGUI=on -DBUILD_TESTS=on -DCMAKE_BUILD_TYPE=Release -DUSE_LIBCXX=off ..

  configure-without-libcxx:
    steps:
      - run:
          command: |
            export "CC=$PWD/third_party/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin/clang"
            export "CXX=$PWD/third_party/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin/clang++"
            mkdir build
            cd build
            cmake -G Ninja -DGUI=on -DBUILD_TESTS=on -DCMAKE_BUILD_TYPE=Release -DUSE_LIBCXX=off ..

  configure-without-curl:
    steps:
      - run:
          command: |
            export "CC=$PWD/third_party/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin/clang"
            export "CXX=$PWD/third_party/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin/clang++"
            mkdir build
            cd build
            cmake -G Ninja -DGUI=on -DBUILD_TESTS=on -DCMAKE_BUILD_TYPE=Release -DUSE_CURL=off ..

  configure-without-nghttp2:
    steps:
      - run:
          command: |
            export "CC=$PWD/third_party/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin/clang"
            export "CXX=$PWD/third_party/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin/clang++"
            mkdir build
            cd build
            cmake -G Ninja -DGUI=on -DBUILD_TESTS=on -DCMAKE_BUILD_TYPE=Release -DUSE_NGHTTP2=off ..

  configure-arm:
    steps:
      - run:
          command: |
            export "CC=clang"
            export "CXX=clang++"
            mkdir build
            cd build
            cmake -G Ninja -DGUI=on -DBUILD_TESTS=on -DCMAKE_BUILD_TYPE=Release ..

  build:
    steps:
      - run:
          command: |
            ninja -C build yass yass_test

  test:
    steps:
      - run: ninja -C build check

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202010-01

jobs:
  basic:
    executor: ubuntu
    steps:
      - checkout
      - update-submodule
      - install-deps
      - download-toolchain
      - configure
      - build
      - test

  basic-gcc:
    executor: ubuntu
    steps:
      - checkout
      - update-submodule
      - install-deps
      - download-toolchain
      - configure-gcc
      - build
      - test

  basic-without-libcxx:
    executor: ubuntu
    steps:
      - checkout
      - update-submodule
      - install-deps
      - download-toolchain
      - configure-without-libcxx
      - build
      - test

  basic-without-curl:
    executor: ubuntu
    steps:
      - checkout
      - update-submodule
      - install-deps
      - download-toolchain
      - configure-without-curl
      - build
      - test

  basic-without-nghttp2:
    executor: ubuntu
    steps:
      - checkout
      - update-submodule
      - install-deps
      - download-toolchain
      - configure-without-nghttp2
      - build
      - test

  arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - update-submodule
      - install-deps
      - download-toolchain-arm
      - configure-arm
      - build
      - test

workflows:
  x64-basic:
    jobs:
      - basic

  x64-basic-gcc:
    jobs:
      - basic-gcc

  x64-basic-without-libcxx:
    jobs:
      - basic-without-libcxx

  x64-basic-without-curl:
    jobs:
      - basic-without-curl

  x64-basic-without-nghttp2:
    jobs:
      - basic-without-nghttp2

  arm-basic:
    jobs:
      - basic
