set(CMAKE_SYSTEM_NAME Android)
#set(CMAKE_SYSTEM_VERSION ${ANDROID_API_VERSION})
#set(CMAKE_ANDROID_ARCH_ABI ${ANDROID_ABI})
#set(CMAKE_ANDROID_NDK ${CMAKE_CURRENT_SOURCE_DIR}/third_party/android_toolchain)
#set(CMAKE_ANDROID_STL_TYPE none)
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_SYSTEM_PROCESSOR "${GCC_SYSTEM_PROCESSOR}" CACHE STRING "")
set(CMAKE_C_COMPILER_TARGET "${GCC_TARGET}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "${GCC_TARGET}" CACHE STRING "")
set(CMAKE_ASM_COMPILER_TARGET "${GCC_TARGET}" CACHE STRING "")

set(CMAKE_AR "${LLVM_SYSROOT}/bin/llvm-ar" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER_AR "${LLVM_SYSROOT}/bin/llvm-ar" CACHE FILEPATH "")
set(CMAKE_RANLIB "${LLVM_SYSROOT}/bin/llvm-ranlib" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER_RANLIB "${LLVM_SYSROOT}/bin/llvm-ranlib" CACHE FILEPATH "")

set(CMAKE_SYSROOT "${CMAKE_CURRENT_SOURCE_DIR}/third_party/android_toolchain/toolchains/llvm/prebuilt/${CURRENT_OS}-x86_64/sysroot" CACHE STRING "")

# set CMAKE_ANDROID_STL_TYPE to none manually
# following /usr/share/cmake/Modules/Platform/Android-Common.cmake
set(CMAKE_CXX_COMPILE_OBJECT
  "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE> -nostdinc++")
string(APPEND CMAKE_CXX_STANDARD_LIBRARIES " -nostdlib++")
