set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "${GCC_SYSTEM_PROCESSOR}" CACHE STRING "")
set(CMAKE_C_COMPILER_TARGET "${GCC_TARGET}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "${GCC_TARGET}" CACHE STRING "")
set(CMAKE_ASM_COMPILER_TARGET "${GCC_TARGET}" CACHE STRING "")

set(CMAKE_AR "${LLVM_SYSROOT}/bin/llvm-ar" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER_AR "${LLVM_SYSROOT}/bin/llvm-ar" CACHE FILEPATH "")
set(CMAKE_RANLIB "${LLVM_SYSROOT}/bin/llvm-ranlib" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER_RANLIB "${LLVM_SYSROOT}/bin/llvm-ranlib" CACHE FILEPATH "")

set(CMAKE_SYSROOT "${GCC_SYSROOT}" CACHE STRING "")
