name: Unused Deprecated Build Artifacts (Flatpak Binary)
on:
  push:
    branches: [master, develop]
    paths-ignore:
    - '**/*.md'
    - '.circleci/**'
    - '.cirrus.yml'
jobs:
  flatpak-release:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Checkout with shallow submodules
        run: |
          # unshallow must come first otherwise submodule may be get unshallowed
          git fetch --tags --unshallow
          git submodule update --init --depth 1
