name: Publish Releases Checksum
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  workflow_run:
    workflows: ['Build Artifacts (Windows)', 'Build Artifacts (macOS)', 'Build Artifacts (Linux)']
    types:
      - completed
jobs:
  publish-checksum:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    if: {{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Get tag name
        run: |
          echo "tag_name=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: List all dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{ env.tag_name }} --json assets -q '.["assets"] | .[] |= .name' > DISTS
          if [ "x$(cat DISTS | grep '.zip' | grep '.rpm' | grep '.deb' | grep '.msi' | grep '.dmg' | head -n 1)" != "x" ]; then
            echo "all_dists_uploaded=1" >> $GITHUB_ENV
          else
            echo "all_dists_uploaded=0" >> $GITHUB_ENV
          fi
          if [ "x$(cat DISTS | grep 'sha256sum' | head -n 1)" != "x" ]; then
            echo "sha256sum_uploaded=1" >> $GITHUB_ENV
          else
            echo "sha256sum_uploaded=0" >> $GITHUB_ENV
          fi
      - name: Download all dist
        if: {{ env.all_dists_uploaded == '1' && env.sha256sum_uploaded == '0' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ env.tag_name }} -p '*.zip' -p '*.rpm' -p '*.deb' -p '*.dmg' -p '*.msi'
      - name: Generate sha256 checksum
        if: {{ env.all_dists_uploaded == '1' && env.sha256sum_uploaded == '0' }}
        run: |
          sha256sum *.zip *.rpm *.deb *.dmg *.msi > yass-${{ env.tag_name }}-sha256sum.txt
      - name: Upload sha256 checksum
        if: {{ env.all_dists_uploaded == '1' && env.sha256sum_uploaded == '0' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ env.tag_name }} yass-${{ env.tag_name }}-sha256sum.txt
