name: OnDemand Build Artifacts (iOS)
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  schedule:
    - cron: '0 16 * * *'
concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}
env:
  CACHE_EPOCH: 128-3
  GOPROXY: direct
jobs:
  ios-simulator-release:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
        build_type: [MinSizeRel]
    env:
      BUILD_TYPE: '${{ matrix.build_type }}'
    steps:
      - uses: actions/checkout@v4
      - name: Checkout with shallow submodules
        run: |
          # unshallow must come first otherwise submodule may be get unshallowed
          git fetch --tags --unshallow
          git submodule update --init --depth 1
      - name: Cache clang
        id: clang-cache
        uses: actions/cache@v4
        with:
          path: |
            third_party/llvm-build/Release+Asserts
          key: ${{ runner.os }}-toolchain-arm64-${{ hashFiles('CLANG_REVISION') }}-v${{ env.CACHE_EPOCH }}
      - name: Cache cargo build stage
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-ios-cargo-${{ hashFiles('third_party/tun2proxy/Cargo.toml') }}-${{ hashFiles('third_party/tun2proxy/Cargo.lock') }}
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.19.0'
      - name: Cache golang (tools only)
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-tools-${{ hashFiles('tools/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-
      - name: Build build tool
        run: |
          cd tools
          go build
      - name: "Install dependency: tun2proxy"
        run: |
          # required by m1 runner
          # https://github.com/actions/runner-images/blob/main/images/macos/scripts/build/install-rust.sh
          rm -rf $HOME/.cargo
          brew install rustup
          rustup-init -y --no-modify-path --default-toolchain=stable --profile=minimal
          source "$HOME/.cargo/env"
          ./scripts/setup-ios-rust.sh
          WITH_OS=ios-sim WITH_CPU=${{ matrix.arch }} ./scripts/build-tun2proxy.sh
      - name: "Install dependency: prebuilt clang and clang-tidy binaries"
        if: ${{ steps.clang-cache.outputs.cache-hit != 'true' }}
        run: |
          ./scripts/download-clang-prebuilt-binaries.py
          rm -f third_party/llvm-build/Release+Asserts/*.tgz
      - name: Populate depedencies
        run: |
          # brew update
          # brew install ninja cmake p7zip
          brew install ninja
      - name: Set up Xcode to 15.4
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Build and Run tests (arm64)
        if: ${{ matrix.arch == 'arm64' }}
        run: |
          ./tools/build --system ios --subsystem simulator --arch ${{ matrix.arch }} -run-test
      - name: Build (non-arm64)
        if: ${{ matrix.arch != 'arm64' }}
        run: |
          ./tools/build --system ios --subsystem simulator --arch ${{ matrix.arch }} -build-test -build-benchmark
